### ISSUE TITLE
May I repost your blog?

### ISSUE THREAD

**Issue by Wang-Jinxu** [zdevito/zdevito.github.io#1]
Hello, Zach, your blog _**Extracting information about CUDA crashes from core dumps**_ is very enlightening. I am wondering if we can translate your blog into Chinese and post it on our WeChat official account platform. We will keep the original link and state where it is translated from. I believe this move will enable more people who are interested in CUDA to be inspired. Thx!

**Comment by zdevito** [comment]
Sorry for the delay, I wasn't watching for posts to this repo. Sure you can translate the article.
